DROP TABLE ARTRP;
DROP TABLE ART;
DROP TABLE ATYPE;
DROP TABLE SHOPAD;
DROP TABLE MALLAD;
DROP TABLE NEWS;
DROP TABLE SHGMRP;
DROP TABLE SHGM;
DROP TABLE SHOPBK;
DROP TABLE SHOPRPDT;
DROP TABLE GMLIST;
DROP TABLE GAME;
DROP TABLE GMTYPEDT ;
DROP TABLE MALLORDT;
DROP TABLE MALLOR;
DROP TABLE GMTYPE;
DROP TABLE MALL;
DROP TABLE AUTHORITY;
DROP TABLE FEATURES;
DROP TABLE TFCORD;
DROP TABLE EMP;
DROP TABLE SHOPRP;
DROP TABLE RATE;
DROP TABLE JOINRM;
DROP TABLE RMINFO;
DROP TABLE SHOP;
DROP TABLE MSG;
DROP TABLE MSGRP;
DROP TABLE MBRPF;
---彥志

CREATE TABLE MBRPF (
 MBRNO      VARCHAR2(7) PRIMARY KEY NOT NULL ,
 MBRACT     VARCHAR2(10) UNIQUE NOT NULL ,
 MBRPW      VARCHAR2(10) NOT NULL ,
 MBRNAME    VARCHAR2(30) NOT NULL ,
 MBRIMG     BLOB,
 BIRTH      DATE,
 SEX        NUMBER(1),
 MAIL       VARCHAR2(30),
 PHONE      VARCHAR2(12),
 MBRAC      VARCHAR2(30),
 NICKNAME   VARCHAR2(24),
 POINTS     NUMBER(7),
 STATUS     NUMBER(1),
 RATEDTOTAL NUMBER(3),
 STARTOTAL  NUMBER(3),
 UNATTEND   NUMBER(3),
 TTATTEND   NUMBER(3)
 );

---鴻基

CREATE TABLE SHOP(
 SHOPNO             VARCHAR2(7) NOT NULL,
 SHOPACT            VARCHAR2(10),
 SHOPPW             VARCHAR2(10),
 SHOPNAME           VARCHAR2(30),
 SHOPLOC            VARCHAR2(150),
 SHOPCY             VARCHAR2(30),
 SHOPPHONE          NUMBER(10),
 SHOPIMG	    BLOB,
 STATUS             NUMBER(1),
 CONSTRAINT SHOP_PRIMARY_KEY PRIMARY KEY (SHOPNO));
 
 
CREATE TABLE SHOPBK(
 SHOPBKNO             VARCHAR2(7) NOT NULL,
 SHOPNO               VARCHAR2(7) NOT NULL,
 OFDTABLE             NUMBER(3),
 SHOPPDS              TIMESTAMP,
 SHOPPDE              TIMESTAMP,
 PAYINFOHR            NUMBER(4),
 PAYINFODAY           NUMBER(5),
 CONSTRAINT SHOPBK_SHOPNO_FK FOREIGN KEY (SHOPNO)  REFERENCES SHOP(SHOPNO),
 CONSTRAINT SHOPBK_PRIMARY_KEY PRIMARY KEY (SHOPBKNO));
 

CREATE TABLE GAME(
 GMNO             VARCHAR2(7) NOT NULL,
 GMNAME           VARCHAR2(30),
 GMIMG 		  BLOB,
 CONSTRAINT GAME_PRIMARY_KEY PRIMARY KEY (GMNO));
 
CREATE TABLE GMLIST(
 GMNO                 VARCHAR2(7) NOT NULL,
 SHOPNO               VARCHAR2(7) NOT NULL,
 CONSTRAINT GMLIST_GMNO_FK FOREIGN KEY (GMNO)  REFERENCES GAME(GMNO),
 CONSTRAINT GMLIST_SHOPNO_FK FOREIGN KEY (SHOPNO)  REFERENCES SHOP(SHOPNO),
 CONSTRAINT GMLIST_PRIMARY_KEY PRIMARY KEY (GMNO, SHOPNO));
 
 
 ---承翰
 CREATE TABLE RMINFO(
RMNO VARCHAR2(7) NOT NULL,
SHOPNO VARCHAR2(7) NOT NULL REFERENCES SHOP(SHOPNO),
CREATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CUTOFF TIMESTAMP NOT NULL,
STATUS NUMBER(1) DEFAULT 0,
NAMING VARCHAR2(30) NOT NULL,
UPLIMIT NUMBER(2) NOT NULL,
LOWLIMIT NUMBER(2) NOT NULL,
STARTTIME TIMESTAMP NOT NULL,
ENDTIME TIMESTAMP NOT NULL,
MBRNO VARCHAR2(7) NOT NULL,
GAME VARCHAR2(150) NOT NULL,
REMARKS VARCHAR2(300) ,
RESTRICTION NUMBER(1) Not Null,
REPORT NUMBER(1) DEFAULT 0,
CONSTRAINT RMINFO_RMNO_PK PRIMARY KEY(RMNO),
CONSTRAINT RMINFO_SHOPNO_FK FOREIGN KEY (SHOPNO) REFERENCES SHOP (SHOPNO),
CONSTRAINT RMINFO_MBRNO_FK FOREIGN KEY (MBRNO) REFERENCES MBRPF (MBRNO)
);
 
 CREATE TABLE SHOPRPDT(
 SHOPRPNO             VARCHAR2(7) NOT NULL,
 RMNO                 VARCHAR2(7) NOT NULL,
 MBRNO                VARCHAR2(7) NOT NULL,
 SHOPNO               VARCHAR2(7) NOT NULL,
 DETAIL               CLOB,
 STATUS               NUMBER(1),
 CONSTRAINT SHOPRPDT_MBRNO_FK FOREIGN KEY (MBRNO) REFERENCES MBRPF(MBRNO),
 CONSTRAINT SHOPRPDT_RMNO_FK FOREIGN KEY (RMNO)  REFERENCES RMINFO(RMNO),
 CONSTRAINT SHOPRPDT_SHOPNO_FK FOREIGN KEY (SHOPNO)  REFERENCES SHOP(SHOPNO),
 CONSTRAINT SHOPRPDT_PRIMARY_KEY PRIMARY KEY (SHOPRPNO)); 
 
CREATE TABLE JOINRM(
MBRNO VARCHAR2(7) NOT NULL,
RMNO VARCHAR2(7) NOT NULL,
RATEREPORT NUMBER(1) DEFAULT 0,
SHOPREPORT NUMBER(1) DEFAULT 0,
CONSTRAINT JOINRM_COMPOUND_KEY PRIMARY KEY(MBRNO, RMNO),
CONSTRAINT JOINRM_MBRNO_FK FOREIGN KEY (MBRNO) REFERENCES MBRPF (MBRNO),
CONSTRAINT JOINRM_RMNO_FK FOREIGN KEY (RMNO) REFERENCES RMINFO (RMNO)
);

CREATE TABLE RATE(
RATENO VARCHAR2(7) NOT NULL,
RMNO VARCHAR2(7) NOT NULL,
RATINGMBRNO VARCHAR2(7) NOT NULL,
RATEDMBRNO VARCHAR2(7) NOT NULL,
DETAIL VARCHAR2(300),
SCORE NUMBER(1) NOT NULL,
RATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT RATE_RATENO_PK PRIMARY KEY(RATENO),
CONSTRAINT RATE_RMNO_FK FOREIGN KEY (RMNO) REFERENCES RMINFO (RMNO),
CONSTRAINT RATE_RATINGMBRNO_FK FOREIGN KEY (RATINGMBRNO) REFERENCES MBRPF (MBRNO),
CONSTRAINT RATE_RATEDMBRNO_FK FOREIGN KEY (RATEDMBRNO) REFERENCES MBRPF (MBRNO)
);

CREATE TABLE SHOPRP(
MBRNO VARCHAR2(7) Not Null,
RMNO VARCHAR2(7) Not Null,
DETAIL VARCHAR2(300),
RPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ATTEND NUMBER(1) NOT NULL,
CONSTRAINT SHOPRP_COMPOUND_KEY PRIMARY KEY(MBRNO, RMNO),
CONSTRAINT SHOPRP_RMNO_FK FOREIGN KEY (RMNO) REFERENCES RMINFO (RMNO),
CONSTRAINT SHOPRP_MBRNO_FK FOREIGN KEY (MBRNO) REFERENCES MBRPF (MBRNO)
);

----采庭---
-----------------
--FOR TABLE EMP--
-----------------

--建立後台管理員表格
CREATE TABLE EMP(
PIC BLOB,
EMPNO VARCHAR2(7) NOT NULL PRIMARY KEY,
EMPNAME VARCHAR2(30) NOT NULL,
EMPPWD VARCHAR2(10) NOT NULL,
MAIL VARCHAR2(30) NOT NULL,
SEX VARCHAR2(6) NOT NULL,
EMPSTATUS VARCHAR2(1) NOT NULL
);

--------------------
--FOR TABLE TFCORD--
--------------------

--建立點數現金兌換紀錄表格
CREATE TABLE TFCORD(
TFNO VARCHAR2(16) NOT NULL PRIMARY KEY,
MBRNO VARCHAR2(7) NOT NULL,
TFTYPE VARCHAR2(1) NOT NULL,
PRICE NUMBER(7) NOT NULL,
TFTIME TIMESTAMP,
TFSTATUS NUMBER(1) NOT NULL
);

----------------------
--FOR TABLE FEATURES--
----------------------

--建立功能列表
CREATE TABLE FEATURES(
FTNO VARCHAR2(7) NOT NULL PRIMARY KEY,
FTNAME VARCHAR2(30) NOT NULL
);

-----------------------
--FOR TABLE AUTHORITY--
-----------------------

--建立權限表格
CREATE TABLE AUTHORITY(
EMPNO VARCHAR2(7) NOT NULL,
FTNO VARCHAR2(7) NOT NULL,
PRIMARY KEY(EMPNO,FTNO),
FOREIGN KEY(EMPNO) REFERENCES EMP(EMPNO),
FOREIGN KEY(FTNO) REFERENCES FEATURES(FTNO)
);



--樹育
CREATE TABLE MALL(
COMMNO      VARCHAR2(7) NOT NULL PRIMARY KEY,
COMMNAME    VARCHAR2(60),
PRICE       NUMBER(7),
QUANTITY    NUMBER(3),
IMG         BLOB,
INTRO       CLOB,
AGE         VARCHAR2(30),
PLAYER      VARCHAR2(30),
STATUS      NUMBER(1)
);

CREATE TABLE MALLOR(
MALLORNO    VARCHAR2(17) NOT NULL PRIMARY KEY ,
MBRNO       VARCHAR2(7)REFERENCES MBRPF (MBRNO),
ORDATE      TIMESTAMP,
TAKE        VARCHAR2(30),
ADDRESS     VARCHAR2(150),
STATUS      NUMBER(1),
PAYSTATUS   NUMBER(1),
BOXSTATUS   NUMBER(1),
PRICE       NUMBER(8)
);

CREATE TABLE MALLORDT(
MALLORNO    VARCHAR2(16)NOT NULL REFERENCES MALLOR(MALLORNO),
COMMNO      VARCHAR2(7) NOT NULL REFERENCES MALL(COMMNO),
QUANTITY    NUMBER(3),
PRICE       NUMBER(7),
PRIMARY KEY(MALLORNO , COMMNO)--複合主建
);

CREATE TABLE GMTYPE(
TYPENO      VARCHAR2(7) NOT NULL PRIMARY KEY ,
TYPENAME    VARCHAR2(30)
);

CREATE TABLE GMTYPEDT(
TYPENO  VARCHAR2(7) NOT NULL REFERENCES GMTYPE(TYPENO),
COMMNO  VARCHAR2(7) NOT NULL REFERENCES MALL(COMMNO),
PRIMARY KEY(COMMNO,TYPENO)
);

--孟辰
CREATE TABLE ATYPE (
ATNO              VARCHAR2(4) NOT NULL,
ATNAME            VARCHAR2(30),
CONSTRAINT ATYPE_PRIMARY_KEY PRIMARY KEY (ATNO));

CREATE TABLE ART (
ARTNO             VARCHAR2(7) NOT NULL,
MBRNO             VARCHAR2(7) NOT NULL,
DETAIL            CLOB,
ARTTT             VARCHAR2(300),
PDATE             DATE,  
STATUS            NUMBER(1),
ATNO              VARCHAR2(4) NOT NULL,
APIC              BLOB,
CONSTRAINT ART_FOREIGN_KEY2 FOREIGN KEY (ATNO) REFERENCES ATYPE (ATNO),
CONSTRAINT ART_PRIMARY_KEY PRIMARY KEY (ARTNO));

CREATE TABLE ARTRP (
ARTRPNO             VARCHAR2(7) NOT NULL,
ARTNO               VARCHAR2(7) NOT NULL,
DETAIL              CLOB,
MBRNO               VARCHAR2(7) NOT NULL,
STATUS              NUMBER(1),

CONSTRAINT ARTRP_FOREIGN_KEY2 FOREIGN KEY (ARTNO) REFERENCES ART (ARTNO),
CONSTRAINT ARTRP_PRIMARY_KEY PRIMARY KEY (ARTRPNO));

CREATE TABLE SHOPAD (
SHOPADNO            VARCHAR2(7) NOT NULL,
SHOPNO              VARCHAR2(7) NOT NULL,
SHOPADTT            VARCHAR2(300),
STARTT              DATE,
STOPT               DATE,
STATUS              NUMBER(1),
CONSTRAINT SHOPAD_FOREIGN_KEY FOREIGN KEY (SHOPNO) REFERENCES SHOP (SHOPNO),
CONSTRAINT SHOPAD_PRIMARY_KEY PRIMARY KEY (SHOPADNO));

CREATE TABLE MALLAD (
MALLADNO            VARCHAR2(7) NOT NULL,
COMMNO              VARCHAR2(7) NOT NULL,
GMADTT              VARCHAR2(300),
DETAIL              BLOB,
STARTT              DATE,
STOPT               DATE,
CONSTRAINT MALLAD_FOREIGN_KEY FOREIGN KEY (COMMNO) REFERENCES MALL (COMMNO),
CONSTRAINT MALLAD_PRIMARY_KEY PRIMARY KEY (MALLADNO));

CREATE TABLE NEWS (
NEWSNO              VARCHAR2(7) NOT NULL,
NEWSTT              VARCHAR2(300),
DETAIL              CLOB,
PDATE               DATE,
CONSTRAINT NEWS_PRIMARY_KEY PRIMARY KEY (NEWSNO));

--柏元


CREATE TABLE SHGM(
SHGMNO  VARCHAR2(7) NOT NULL,
SELLERNO  VARCHAR2(7) NOT NULL,
BUYERNO  VARCHAR2(7),
SHGMNAME VARCHAR2 (50),
PRICE NUMBER(6),
INTRO CLOB,
IMG BLOB,
UPCHECK NUMBER(1),
UPTIME TIMESTAMP,
TAKE VARCHAR2(30),
TAKERNM VARCHAR2(30),
TAKERPH VARCHAR2(10),
ADDRESS VARCHAR2(150),
BOXSTATUS NUMBER(1),
PAYSTATUS NUMBER(1),
STATUS NUMBER(1),
SOLDTIME TIMESTAMP,
CONSTRAINT SHGM_SHGMNO_PK PRIMARY KEY (SHGMNO),
CONSTRAINT SHGMRP_SELLERNO_FK FOREIGN KEY (SELLERNO) REFERENCES MBRPF (MBRNO),
CONSTRAINT SHGMRP_BUYERNO_FK FOREIGN KEY (BUYERNO) REFERENCES MBRPF (MBRNO));

CREATE TABLE SHGMRP(
SHGMRPNO VARCHAR2(7) NOT NULL,
SHGMNO VARCHAR2(7) NOT NULL,
SUITERNO VARCHAR2(7) NOT NULL,
DETAIL CLOB,
STATUS NUMBER(1),
CONSTRAINT SHGMRP_SHGMRPNO_PK PRIMARY KEY (SHGMRPNO),
CONSTRAINT SHGMRP_SHGMNO_FK FOREIGN KEY (SHGMNO) REFERENCES SHGM (SHGMNO),
CONSTRAINT SHGMRP_SUITERNO_FK FOREIGN KEY (SUITERNO) REFERENCES MBRPF (MBRNO));

---彥志
CREATE TABLE MSGRP (
MSGRPNO VARCHAR2(7) PRIMARY KEY NOT NULL,
MSGNO VARCHAR2(7) NOT NULL,
DETAIL CLOB,
MBRNO VARCHAR2(7) NOT NULL,
STATUS NUMBER(1)
,FOREIGN KEY (MBRNO) REFERENCES MBRPF (MBRNO)
);

CREATE TABLE MSG (
MSGNO VARCHAR2(7) PRIMARY KEY NOT NULL,
MBRNO VARCHAR2(7) NOT NULL,
DETAIL CLOB,
ARTNO VARCHAR2(7) NOT NULL,
STATUS NUMBER(1),
FOREIGN KEY (MBRNO) REFERENCES MBRPF (MBRNO)
);